### ISSUE TITLE
gstatus returned non-zero exit status 16

### ISSUE THREAD

**Issue by ach-nke** [MrCirca/zabbix-glusterfs#2]
A couple time per hour I'm receiving this error message:

```
Traceback (most recent call last):
  File "/opt/scripts/zabbix-glusterfs/gstatus_discovery.py", line 7, in <module>
    gstatus_output = subprocess.check_output('gstatus -a -o json ', shell=True).decode()
  File "/usr/lib64/python3.4/subprocess.py", line 617, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command 'gstatus -a -o json ' returned non-zero exit status 16
```

Anyone else experiencing it?

![image](https://user-images.githubusercontent.com/39748067/43218261-817a5620-9009-11e8-9421-d76cc6ccb1ba.png)

**Comment by ach-nke** [comment]
I found solution to this problem. It's related to gstatus randomly timing out. See https://github.com/gluster/gstatus/pull/4.
You have to call gstatus with specifying custom timeout threshold: `gstatus -a -t 10 -o json`.

**Comment by ach-nke** [comment]
I had to reduce the frequency of volume health check from 30s to 2min. Apparently gstatus was overwhelming the system with simultaneous requests.
